### ISSUE TITLE
wattcher.py: "Watt draw, in VA"

### ISSUE THREAD

**Issue by pdp7** [adafruit/Tweet-a-Watt#2]
The wattcher.py script for the Tweet-A-Watt displays the "Watt draw, in VA".  I find this to be ambiguous as to whether this value represents real or apparent power.  The Kill-A-Watt has a VA mode (I assume apparent power) and a Watt mode (I assume real power).  I'm uncertain which mode should be used to verify the  "Watt draw, in VA" output from wattcher.py.  thanks!

**Comment by ladyada** [comment]
tweet a watt provides best-guess true wattage, no 'power correction factor' required as both V and A are measured

**Comment by pdp7** [comment]
One quick clarification if you have a moment: ideally, should wattcher.py's  "Watt draw, in VA" value correspond to the Kill-A-Watt's VA mode reading or the Watt mode reading?  thanks!

**Comment by ladyada** [comment]
No idea, check the KaW documentation and/or website, they can help you with supporting their product.

If you have further questions about TaW, please post them in the forum, github is best used for code bugs, fixes & updates, not tech support and general questions. 

thanks!
